const getAlertClass = (status) => {
  if (status === "EXPIRED") return "bg-red-500/10 text-red-600 dark:text-red-300 border-red-500/20";
  if (status === "EXPIRING_7_DAYS") return "bg-orange-500/10 text-orange-600 dark:text-orange-300 border-orange-500/20";
  if (status === "EXPIRING_15_DAYS" || status === "EXPIRING_30_DAYS") return "bg-yellow-500/10 text-yellow-700 dark:text-yellow-300 border-yellow-500/20";
  return "bg-tanta-primary/15 text-tanta-secondary dark:text-[#f0b36d] border-tanta-primary/25";
};
function InventoryExpirationAlerts({ alerts = [], loading, formatNumber }) {
  return <div className="rounded-2xl bg-[#F3EFDC]/85 dark:bg-[#1e1422]/90 border border-tanta-primary/25 dark:border-tanta-primary/35 shadow-card overflow-hidden"><div className="p-5 border-b border-tanta-primary/15"><h2 className="text-xl font-bold">Alertas de vencimiento</h2><p className="text-sm opacity-65 mt-1">Lotes vencidos, próximos a vencer o sin fecha de vencimiento.</p></div><div className="overflow-x-auto custom-scrollbar"><table className="w-full min-w-[1080px] table-fixed text-left"><thead className="bg-tanta-dark dark:bg-gradient-to-r dark:from-tanta-primary dark:to-[#56599A] text-white"><tr><th className="p-4 w-[190px]">Lote</th><th className="p-4 w-[260px]">Insumo</th><th className="p-4 w-[180px]">Ubicación</th><th className="p-4 w-[160px]">Stock</th><th className="p-4 w-[120px]">Unidad</th><th className="p-4 w-[160px]">Vencimiento</th><th className="p-4 w-[190px]">Estado</th></tr></thead><tbody>{alerts.map((item) => <tr key={`${item.lot_id}-${item.ingredient_id}`} className="border-t border-tanta-primary/15 dark:border-tanta-primary/20 hover:bg-tanta-primary/10 transition"><td className="p-4 font-medium">{item.lot_code || "-"}</td><td className="p-4"><div className="truncate" title={item.ingredient_name}>{item.ingredient_code} - {item.ingredient_name}</div></td><td className="p-4 opacity-80">{item.location_name}</td><td className="p-4 font-semibold text-tanta-secondary dark:text-[#f0b36d]">{formatNumber(item.stock_quantity)}</td><td className="p-4">{item.unit_code}</td><td className="p-4">{item.expiration_date || "-"}</td><td className="p-4"><span className={`px-3 py-1 rounded-full text-xs border whitespace-nowrap ${getAlertClass(item.expiration_status)}`}>{item.expiration_status}</span></td></tr>)}{!loading && alerts.length === 0 && <tr><td colSpan="7" className="p-8 text-center opacity-60">No hay alertas de vencimiento.</td></tr>}{loading && <tr><td colSpan="7" className="p-8 text-center opacity-60">Cargando alertas...</td></tr>}</tbody></table></div></div>;
}
export default InventoryExpirationAlerts;
