import { Search } from "lucide-react";

const getStatusClass = (status) => {
  if (status === "AVAILABLE") return "bg-green-500/10 text-green-600 dark:text-green-300 border-green-500/20";
  if (status === "EXPIRED" || status === "BLOCKED") return "bg-red-500/10 text-red-600 dark:text-red-300 border-red-500/20";
  return "bg-tanta-primary/15 text-tanta-secondary dark:text-[#f0b36d] border-tanta-primary/25";
};

function InventoryLots({ lots = [], search, setSearch, loading, formatNumber, formatCurrency }) {
  return <div className="rounded-2xl bg-[#F3EFDC]/85 dark:bg-[#1e1422]/90 border border-tanta-primary/25 dark:border-tanta-primary/35 shadow-card overflow-hidden">
    <div className="p-5 flex flex-col md:flex-row gap-4 md:items-center md:justify-between border-b border-tanta-primary/15"><div><h2 className="text-xl font-bold">Lotes</h2><p className="text-sm opacity-65 mt-1">Control de lotes, vencimientos y stock por lote.</p></div><div className="flex items-center gap-2 bg-tanta-bg/70 dark:bg-tanta-primary/12 rounded-xl px-4 py-3 w-full md:w-[340px] border border-transparent dark:border-tanta-primary/20 focus-within:border-tanta-primary/60 transition"><Search size={18} className="text-tanta-primary dark:text-[#f0b36d]" /><input className="bg-transparent outline-none w-full placeholder:text-tanta-dark/50 dark:placeholder:text-tanta-darkText/50" placeholder="Buscar lote o insumo..." value={search} onChange={(e) => setSearch(e.target.value)} /></div></div>
    <div className="overflow-x-auto custom-scrollbar"><table className="w-full min-w-[1380px] table-fixed text-left"><thead className="bg-tanta-dark dark:bg-gradient-to-r dark:from-tanta-primary dark:to-[#56599A] text-white"><tr><th className="p-4 w-[180px]">Lote</th><th className="p-4 w-[260px]">Insumo</th><th className="p-4 w-[200px]">Proveedor</th><th className="p-4 w-[180px]">Ubicación</th><th className="p-4 w-[150px]">Stock actual</th><th className="p-4 w-[120px]">Unidad</th><th className="p-4 w-[150px]">Costo unit.</th><th className="p-4 w-[150px]">Ingreso</th><th className="p-4 w-[150px]">Vencimiento</th><th className="p-4 w-[130px]">Estado</th></tr></thead><tbody>{lots.map((item) => <tr key={item.lot_id} className="border-t border-tanta-primary/15 dark:border-tanta-primary/20 hover:bg-tanta-primary/10 transition"><td className="p-4 font-medium">{item.lot_code}</td><td className="p-4"><div className="truncate" title={item.ingredient_name}>{item.ingredient_code} - {item.ingredient_name}</div></td><td className="p-4 opacity-80"><div className="truncate" title={item.supplier_name || "-"}>{item.supplier_name || "-"}</div></td><td className="p-4 opacity-80">{item.location_name}</td><td className="p-4 font-semibold text-tanta-secondary dark:text-[#f0b36d]">{formatNumber(item.current_stock)}</td><td className="p-4">{item.unit_code}</td><td className="p-4">{formatCurrency(item.unit_cost, item.currency_code || "PEN")}</td><td className="p-4">{item.received_date || "-"}</td><td className="p-4">{item.expiration_date || "-"}</td><td className="p-4"><span className={`px-3 py-1 rounded-full text-xs border whitespace-nowrap ${getStatusClass(item.lot_status)}`}>{item.lot_status}</span></td></tr>)}{!loading && lots.length === 0 && <tr><td colSpan="10" className="p-8 text-center opacity-60">No hay lotes registrados.</td></tr>}{loading && <tr><td colSpan="10" className="p-8 text-center opacity-60">Cargando lotes...</td></tr>}</tbody></table></div>
  </div>;
}

export default InventoryLots;
